/* This file was generated by syncqt. */
#ifndef QT_QTSCXML_VERSION_H
#define QT_QTSCXML_VERSION_H

#define QTSCXML_VERSION_STR "6.2.3"

#define QTSCXML_VERSION 0x060203

#endif // QT_QTSCXML_VERSION_H
