/* This file was generated by syncqt. */
#ifndef QT_QTLOCATION_VERSION_H
#define QT_QTLOCATION_VERSION_H

#define QTLOCATION_VERSION_STR "5.15.3"

#define QTLOCATION_VERSION 0x050F03

#endif // QT_QTLOCATION_VERSION_H
