/* This file was generated by syncqt. */
#ifndef QT_QT3DINPUT_VERSION_H
#define QT_QT3DINPUT_VERSION_H

#define QT3DINPUT_VERSION_STR "5.13.1"

#define QT3DINPUT_VERSION 0x050D01

#endif // QT_QT3DINPUT_VERSION_H
