/* This file was generated by syncqt. */
#ifndef QT_QTQMLDEBUG_VERSION_H
#define QT_QTQMLDEBUG_VERSION_H

#define QTQMLDEBUG_VERSION_STR "6.2.3"

#define QTQMLDEBUG_VERSION 0x060203

#endif // QT_QTQMLDEBUG_VERSION_H
