/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "6.2.3"

#define QT3DCORE_VERSION 0x060203

#endif // QT_QT3DCORE_VERSION_H
